const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');
require('./connection');
require('./cache');
require('./broker');
const PORT = process.env.PORT || 8080;
const app = express();
app.use(cors());
app.use(bodyParser.json());
app.use('/readings', require('./routes/readings'));
app.use('/devices', require('./routes/devices'));
app.use('/users', require('./routes/users'));
app.use('/cmnd', require('./routes/cmnd'));
app.listen(PORT, () => { console.log(`Server running on port ${PORT}`); });