#!/bin/bash

IMAGE_NAME=nodered/node-red

MODBUS_PORT=10502

CONTAINER_NAME=modbus
CONTAINER_DIRECTORY=/data
CONTAINER_PORT=1880
CONTAINER_MODBUS_PORT=$MODBUS_PORT

MACHINE_DIRECTORY=$PWD/data
MACHINE_PORT=9001
MACHINE_MODBUS_PORT=$MODBUS_PORT

if [ ! -d "$MACHINE_DIRECTORY" ];
then
    echo "creating 'data' folder..."
    mkdir data
fi
docker run \
--rm \
-it \
-p $MACHINE_PORT:$CONTAINER_PORT \
-p $MACHINE_MODBUS_PORT:$CONTAINER_MODBUS_PORT \
-v $MACHINE_DIRECTORY:$CONTAINER_DIRECTORY \
$IMAGE_NAME